/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Digital Magistrate design system ──────────────────────────────
        // Extracted verbatim from the new HTML design mockups.
        // Based on Material Design 3 dark-mode token naming.
        "on-secondary":              "#402d00",
        "on-primary":                "#243141",
        "surface-tint":              "#bac8dc",
        "on-tertiary-fixed-variant": "#572e99",
        "background":                "#131315",
        "inverse-surface":           "#e4e2e3",
        "surface-container-low":     "#1b1b1d",
        "surface-container-high":    "#2a2a2b",
        "surface-container-highest": "#343536",
        "on-secondary-container":    "#6d5000",
        "tertiary-fixed":            "#ebdcff",
        "on-primary-fixed":          "#0f1c2c",
        "on-surface-variant":        "#c4c6cc",
        "tertiary-fixed-dim":        "#d4bbff",
        "on-error":                  "#690005",
        "secondary-container":       "#ffbf00",
        "primary-fixed-dim":         "#bac8dc",
        "on-primary-container":      "#768497",
        "primary":                   "#bac8dc",
        "on-tertiary-fixed":         "#260058",
        "on-secondary-fixed":        "#261a00",
        "outline-variant":           "#44474c",
        "error-container":           "#93000a",
        "on-tertiary":               "#3f0f81",
        "secondary-fixed-dim":       "#fbbc00",
        "surface-variant":           "#343536",
        "surface-dim":               "#131315",
        "on-tertiary-container":     "#956eda",
        "outline":                   "#8e9196",
        "on-secondary-fixed-variant":"#5c4300",
        "inverse-primary":           "#525f71",
        "tertiary":                  "#d4bbff",
        "surface-bright":            "#39393a",
        "on-primary-fixed-variant":  "#3a4859",
        "on-error-container":        "#ffdad6",
        "secondary":                 "#ffe2ab",
        "tertiary-container":        "#250055",
        "on-surface":                "#e4e2e3",
        "on-background":             "#e4e2e3",
        "secondary-fixed":           "#ffdfa0",
        "primary-fixed":             "#d6e4f9",
        "surface-container":         "#1f2021",
        "surface":                   "#131315",
        "error":                     "#ffb4ab",
        "primary-container":         "#0d1b2a",
        "surface-container-lowest":  "#0e0e0f",
        "inverse-on-surface":        "#303032",
        "scrim":                     "#000000",
      },
      borderRadius: {
        // Matches the design mockups — NOTE: lg < md is intentional
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "0.75rem",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
