"""add_firebase_auth_fields

Revision ID: 029ebe5cfb96
Revises:     d6e0ed912bd5
Create Date: 2026-03-11 19:48:25.952415
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029ebe5cfb96'
down_revision: Union[str, None] = 'd6e0ed912bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('role_approved_by', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('role_approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_users_firebase_uid', 'users', ['firebase_uid'], unique=False)
    op.create_unique_constraint(None, 'users', ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_firebase_uid', table_name='users')
    op.drop_column('users', 'role_approved_at')
    op.drop_column('users', 'role_approved_by')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###
