"""initial_schema

Revision ID: 0513a32dd83f
Revises:
Create Date: 2026-04-06 05:49:29.194772
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0513a32dd83f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_catalog",
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("form_name", sa.String(length=500), nullable=False),
        sa.Column("form_slug", sa.String(length=500), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("file_type", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="active",
            nullable=False,
            comment="Status: active or archived",
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("current_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("needs_human_review", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("preprocessing_flags", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last content change (hash change or new form). Not updated on rename or translation.",
        ),
        sa.CheckConstraint("status IN ('active', 'archived')", name="form_catalog_status_check"),
        sa.PrimaryKeyConstraint("form_id"),
        sa.UniqueConstraint("form_slug"),
    )
    op.create_index("idx_form_catalog_slug", "form_catalog", ["form_slug"], unique=False)
    op.create_index("idx_form_catalog_status", "form_catalog", ["status"], unique=False)
    op.create_table(
        "roles",
        sa.Column("role_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("role_name"),
    )
    op.create_table(
        "form_appearances",
        sa.Column("appearance_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("division", sa.String(length=255), nullable=False),
        sa.Column("section_heading", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form_catalog.form_id"],
        ),
        sa.PrimaryKeyConstraint("appearance_id"),
        sa.UniqueConstraint(
            "form_id", "division", "section_heading", name="form_appearances_form_id_division_section_heading_key"
        ),
    )
    op.create_index("idx_form_appearances_division", "form_appearances", ["division"], unique=False)
    op.create_index("idx_form_appearances_form_id", "form_appearances", ["form_id"], unique=False)
    op.create_table(
        "form_versions",
        sa.Column("version_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("file_type", sa.String(length=10), nullable=False),
        sa.Column("file_path_original", sa.Text(), nullable=False),
        sa.Column("file_path_es", sa.Text(), nullable=True),
        sa.Column("file_path_pt", sa.Text(), nullable=True),
        sa.Column("file_type_es", sa.String(length=10), nullable=True),
        sa.Column("file_type_pt", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form_catalog.form_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint("form_id", "version", name="form_versions_form_id_version_key"),
    )
    op.create_index("idx_form_versions_form_id", "form_versions", ["form_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("firebase_uid", sa.String(length=128), nullable=True, comment="Firebase user ID"),
        sa.Column(
            "auth_provider",
            sa.String(length=50),
            server_default="password",
            nullable=False,
            comment="Auth method: google.com, microsoft.com, password, saml.massgov",
        ),
        sa.Column("email_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("role_approved_by", sa.UUID(), nullable=True),
        sa.Column("role_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_approved_by"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.role_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("firebase_uid"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_index("idx_users_firebase_uid", "users", ["firebase_uid"], unique=False)
    op.create_table(
        "role_requests",
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("requested_role_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name="check_role_request_status"),
        sa.ForeignKeyConstraint(
            ["requested_role_id"],
            ["roles.role_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index("idx_role_requests_status", "role_requests", ["status"], unique=False)
    op.create_index("idx_role_requests_user_id", "role_requests", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False, comment="realtime or document"),
        sa.Column(
            "target_language",
            sa.String(length=20),
            nullable=False,
            comment="spa_Latn or por_Latn. One session = one language always.",
        ),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('active', 'processing', 'completed', 'failed')", name="sessions_status_check"),
        sa.CheckConstraint("target_language IN ('spa_Latn', 'por_Latn')", name="sessions_target_language_check"),
        sa.CheckConstraint("type IN ('realtime', 'document')", name="sessions_type_check"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index("idx_sessions_status", "sessions", ["status"], unique=False)
    op.create_index("idx_sessions_user_id", "sessions", ["user_id"], unique=False)
    op.create_table(
        "document_translation_requests",
        sa.Column("doc_request_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "input_file_gcs_path",
            sa.Text(),
            nullable=False,
            comment="GCS path of the uploaded original. Reused for second-language requests.",
        ),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 of uploaded file bytes. Nullable for legacy rows; required for all new inserts.",
        ),
        sa.Column(
            "target_language",
            sa.String(length=20),
            nullable=False,
            comment="Denormalized from session for query convenience",
        ),
        sa.Column("classification_result", sa.String(length=20), nullable=True, comment="LEGAL or NOT_LEGAL"),
        sa.Column("avg_confidence_score", sa.Float(), nullable=True),
        sa.Column("pii_findings_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("llama_corrections_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("processing_time_seconds", sa.Float(), nullable=True),
        sa.Column("output_file_gcs_path", sa.Text(), nullable=True),
        sa.Column("signed_url", sa.Text(), nullable=True),
        sa.Column("signed_url_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="processing", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "classification_result IS NULL OR classification_result IN ('LEGAL', 'NOT_LEGAL')",
            name="doc_requests_classification_check",
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed', 'rejected')", name="doc_requests_status_check"
        ),
        sa.CheckConstraint("target_language IN ('spa_Latn', 'por_Latn')", name="doc_requests_target_language_check"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("doc_request_id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index("idx_doc_requests_content_hash", "document_translation_requests", ["content_hash"], unique=False)
    op.create_index("idx_doc_requests_session_id", "document_translation_requests", ["session_id"], unique=False)
    op.create_table(
        "pipeline_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("step_name", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("detail", sa.Text(), server_default="", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('running', 'success', 'failed', 'skipped')", name="pipeline_steps_status_check"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "step_name", name="pipeline_steps_session_step_key"),
    )
    op.create_index("idx_pipeline_steps_session_id", "pipeline_steps", ["session_id"], unique=False)
    op.create_table(
        "realtime_translation_requests",
        sa.Column("rt_request_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "room_code",
            sa.String(length=8),
            nullable=False,
            comment="Short alphanumeric join code e.g. A3K7P2. Valid until room_code_expires_at or phase→active.",
        ),
        sa.Column(
            "room_code_expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="30 minutes from creation. Code rejected after this even if phase is still 'waiting'.",
        ),
        sa.Column("court_division", sa.String(length=100), nullable=True),
        sa.Column("courtroom", sa.String(length=50), nullable=True),
        sa.Column("case_docket", sa.String(length=50), nullable=True),
        sa.Column(
            "consent_acknowledged",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Court official confirmed both parties consent before starting.",
        ),
        sa.Column("creator_user_id", sa.UUID(), nullable=False, comment="court_official who created the room."),
        sa.Column(
            "partner_user_id",
            sa.UUID(),
            nullable=True,
            comment="LEP individual's user_id if they signed in. NULL if they joined as a guest.",
        ),
        sa.Column(
            "partner_name",
            sa.String(length=100),
            nullable=True,
            comment="LEP individual's name typed by court official at setup. Used as display name for guests.",
        ),
        sa.Column(
            "partner_joined_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the LEP individual joined. NULL until joined.",
        ),
        sa.Column("phase", sa.String(length=20), server_default="waiting", nullable=False),
        sa.Column(
            "transcript_gcs_path",
            sa.Text(),
            nullable=True,
            comment="gs://courtaccess-ai-transcripts/{session_id}/transcript.json. Set on session end.",
        ),
        sa.Column("transcript_signed_url", sa.Text(), nullable=True),
        sa.Column("transcript_signed_url_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_utterances", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("phase IN ('waiting', 'active', 'ended')", name="rt_requests_phase_check"),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rt_request_id"),
        sa.UniqueConstraint("room_code"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index("idx_rt_requests_phase", "realtime_translation_requests", ["phase"], unique=False)
    op.create_index("idx_rt_requests_room_code", "realtime_translation_requests", ["room_code"], unique=False)
    op.create_index("idx_rt_requests_session_id", "realtime_translation_requests", ["session_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("audit_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("doc_request_id", sa.UUID(), nullable=True),
        sa.Column("rt_request_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_request_id"], ["document_translation_requests.doc_request_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["rt_request_id"], ["realtime_translation_requests.rt_request_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index("idx_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index("idx_audit_logs_session_id", "audit_logs", ["session_id"], unique=False)
    op.create_index("idx_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)

    op.execute("""
    INSERT INTO roles (role_id, role_name, description) VALUES
    (1, 'public',         'Default role, basic document translation and form access'),
    (2, 'court_official', 'Real-time speech translation access'),
    (3, 'interpreter',    'Side-by-side translation review and correction'),
    (4, 'admin',          'Full system access, user management, monitoring')
    ON CONFLICT (role_name) DO NOTHING
    """)

    # Advance the sequence past the highest explicitly-seeded role_id so that
    # future INSERT statements (without an explicit role_id) never collide.
    # is_called=true means the next nextval() call returns MAX(role_id)+1.
    op.execute("SELECT setval('roles_role_id_seq', (SELECT MAX(role_id) FROM roles), true)")

    op.execute("""
       INSERT INTO users (user_id, email, name, role_id, firebase_uid, auth_provider, email_verified, mfa_enabled)
       VALUES ('00000000-0000-0000-0000-000000000001', 'airflow-system@courtaccess.internal', 'Airflow System', 4, NULL, 'system', true, false)
       ON CONFLICT (email) DO NOTHING
   """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_audit_logs_user_id", table_name="audit_logs")
    op.drop_index("idx_audit_logs_session_id", table_name="audit_logs")
    op.drop_index("idx_audit_logs_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("idx_rt_requests_session_id", table_name="realtime_translation_requests")
    op.drop_index("idx_rt_requests_room_code", table_name="realtime_translation_requests")
    op.drop_index("idx_rt_requests_phase", table_name="realtime_translation_requests")
    op.drop_table("realtime_translation_requests")
    op.drop_index("idx_pipeline_steps_session_id", table_name="pipeline_steps")
    op.drop_table("pipeline_steps")
    op.drop_index("idx_doc_requests_session_id", table_name="document_translation_requests")
    op.drop_index("idx_doc_requests_content_hash", table_name="document_translation_requests")
    op.drop_table("document_translation_requests")
    op.drop_index("idx_sessions_user_id", table_name="sessions")
    op.drop_index("idx_sessions_status", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("idx_role_requests_user_id", table_name="role_requests")
    op.drop_index("idx_role_requests_status", table_name="role_requests")
    op.drop_table("role_requests")
    op.drop_index("idx_users_firebase_uid", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_form_versions_form_id", table_name="form_versions")
    op.drop_table("form_versions")
    op.drop_index("idx_form_appearances_form_id", table_name="form_appearances")
    op.drop_index("idx_form_appearances_division", table_name="form_appearances")
    op.drop_table("form_appearances")
    op.drop_table("roles")
    op.drop_index("idx_form_catalog_status", table_name="form_catalog")
    op.drop_index("idx_form_catalog_slug", table_name="form_catalog")
    op.drop_table("form_catalog")
    # ### end Alembic commands ###
