"""add last_updated_at to form_catalog

Revision ID: 64c7ad1631e8
Revises:     a714a2e44840
Create Date: 2026-03-28 21:02:15.268963
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64c7ad1631e8"
down_revision: str | None = "a714a2e44840"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_catalog",
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last content change (hash change or new form). Not updated on rename or translation.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_catalog", "last_updated_at")
    # ### end Alembic commands ###
