"""add_firebase_auth_fields

Revision ID: d6e0ed912bd5
Revises:     001
Create Date: 2026-03-11 17:24:06.178423
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6e0ed912bd5'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=64),
               comment="'user', 'document', 'form', 'session', 'dag'",
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(length=256),
               comment='UUID of the affected resource as a string',
               existing_nullable=True)
    op.alter_column('form_catalog', 'form_id',
               existing_type=sa.UUID(),
               comment='UUID assigned by form_scraper_dag on first scrape',
               existing_nullable=False)
    op.alter_column('form_catalog', 'versions_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full versions array from form_catalog.json',
               existing_nullable=True)
    op.alter_column('translation_requests', 'target_languages',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=8)),
               comment="e.g. ['es', 'pt']",
               existing_nullable=True)
    op.alter_column('translation_requests', 'translated_uris',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{"es": "gs://courtaccess-translated/...", "pt": "gs://..."}',
               existing_nullable=True)
    op.alter_column('translation_requests', 'legal_review_status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{"es": "ok", "pt": "skipped"}',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation_requests', 'legal_review_status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"es": "ok", "pt": "skipped"}',
               existing_nullable=True)
    op.alter_column('translation_requests', 'translated_uris',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"es": "gs://courtaccess-translated/...", "pt": "gs://..."}',
               existing_nullable=True)
    op.alter_column('translation_requests', 'target_languages',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=8)),
               comment=None,
               existing_comment="e.g. ['es', 'pt']",
               existing_nullable=True)
    op.alter_column('form_catalog', 'versions_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full versions array from form_catalog.json',
               existing_nullable=True)
    op.alter_column('form_catalog', 'form_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID assigned by form_scraper_dag on first scrape',
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(length=256),
               comment=None,
               existing_comment='UUID of the affected resource as a string',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment="'user', 'document', 'form', 'session', 'dag'",
               existing_nullable=True)
    # ### end Alembic commands ###
